apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner-app
  namespace: phishing-url-scanner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scanner-app
  template:
    metadata:
      labels:
        app: scanner-app
    spec:
      containers:
        - name: scanner-app
          image: wongyx/phishing-url-scanner:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: VIRUSTOTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: VIRUSTOTAL_API_KEY
            - name: SAFE_BROWSING_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SAFE_BROWSING_API_KEY
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3