apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - serviceaccount.yml
  - configmap.yml
  - secret.yml
  - networkpolicy.yml
  - ingress.yml
  - deployment.yml
  - service.yml
  - hpa.yml