apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - postgres/namespace.yml
  - postgres/serviceaccount.yml
  - postgres/configmap.yml
  - postgres/secret.yml
  - postgres/service.yml
  - postgres/statefulset.yml