name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - "**.go"
              - "go.mod"
              - "go.sum"
              - ".golangci.yml"
              - ".github/workflows/ci.yml"

  lint:
    name: Lint
    needs: changes
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.3
          args: --config=.golangci.yml ./...

  test:
    name: Unit-Test
    needs: [changes, lint]
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - name: Run tests
        run: go test -race ./...

  semgrep:
    name: Semgrep SAST
    needs: changes
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config "p/golang" --sarif-output=semgrep.sarif --severity ERROR .
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  ci:
    name: CI
    if: ${{ always() }}
    needs: [lint, test, semgrep]
    runs-on: ubuntu-latest
    steps:
      - name: Check all jobs passed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
